### ISSUE TITLE
No code link for Ptolemy's theorem

### ISSUE THREAD

**Issue by palmskog** [coq-community/coq100#11]
Despite some searching, I can't find any Coq code at all for Ptolemy's theorem (95), although there is a [publication](http://hal.inria.fr/inria-00585203). Since Coq is about "reproducible" (locally checkable) proofs, I don't think it's enough to claim that something "has been proved in Coq", for inclusion in the list - the code has to be available as well for anyone interested. Hence, I think entry 95 should be removed until the code becomes available.

**Comment by ybertot** [comment]
The code is available now in https://github.com/ybertot/HighSchoolGeometry/tree/adding-ptolemy, pending review and integration in https://github.com/coq-community/HighSchoolGeometry

**Comment by jmadiot** [comment]
Thank you @ybertot and Tuan-Minh Pham for replying so quickly :)
