### ISSUE TITLE
Linking to GitHub in index.html for hosted files

### ISSUE THREAD

**Issue by palmskog** [coq-community/coq100#15]
When clicking on links to "hosted" Coq files, this currently leads to an unfriendly download prompt (example: https://madiot.fr/coq100/inclusionexclusion.v).

A better and more user-friendly solution is to use GitHub links for such files, as already done for other files on GitHub (example: https://github.com/coq-community/coq100/blob/master/inclusionexclusion.v). Then, a user who really wants the file can use the "Raw" button on GitHub.

@jmadiot would you be OK with this change?

**Comment by jmadiot** [comment]
Sure, that's probably best.
